### ISSUE TITLE
set up the MoCo v2 pretraining pipeline (RESISC-45)

### ISSUE THREAD

**Issue by taeil** [Berkeley-Data/irrigation_detection#92]
- using RESISC-45 dataset 
- track experiment on wandb (new project) 

The goal is to familiarize us with the code. 
Everyone should do at least one run. 

- []

**Comment by TsungChinHanKen** [comment]
- Confirmed the pre-trained run on RESISC via @llano from my end
- haven't integrated the wandb

**Comment by suryatechie** [comment]
**I am getting error:**
(base) ➜  hpt git:(ernesto_branch) ✗cd OpenSelfSup
(base) ➜  OpenSelfSup git:(ernesto_branch) ✗.**/tools/dist_train.sh configs/selfsup/moco/r50_v2_resisc_in_basetrain_20ep.py 4**
/scratch/crguest/miniconda3/bin/python: Error while finding module specification for 'torch.distributed.launch' (ModuleNotFoundError: No module named 'torch')
(base) ➜  OpenSelfSup git:(master) ✗

**Comment by TsungChinHanKen** [comment]
Please make sure to run on hp120 by conda activate hp120. not on the base level

**Comment by suryatechie** [comment]
It works fine by following the steps:
1) Login (It will automatically take us to /scratch/crguest/hpt )
2) conda activate hp120
3) Then follow the steps from 'Verify Install' in the git

**Comment by TsungChinHanKen** [comment]
yep, Coloroda has setup the environment, we don't need to reinstal lnstall the torch and cuda ourselves (at lease on his machine)

**Comment by TsungChinHanKen** [comment]
I will help setup the wandb for this one

**Comment by suryatechie** [comment]
I am getting the follwoing error (even after I tried to re-login): 
 File "tools/train.py", line 156, in <module>
    main()
  File "tools/train.py", line 93, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 17, in init_dist
    main()
  File "tools/train.py", line 93, in main
    _init_dist_pytorch(backend, **kwargs)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 30, in _init_dist_pytorch
    init_dist(args.launcher, **cfg.dist_params)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 17, in init_dist
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
    _init_dist_pytorch(backend, **kwargs)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 30, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "tools/train.py", line 156, in <module>

**Comment by oropezaev** [comment]
That's the same error. It's like it is not recognizing the number of GPUs

**Comment by suryatechie** [comment]
Something happened. It's not able to get the GPUs: **No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'**

**Comment by TsungChinHanKen** [comment]
torch.cuda.is_available() return False now, seems that has been modified..trying to see if passing CUDA_VISIBLE_DEVICES=0,1,2,3 would work

**Comment by suryatechie** [comment]
Tried **CUDA_VISIBLE_DEVICES=0,1,2,3 ./tools/dist_train.sh configs/selfsup/moco/r50_v2_resisc_in_basetrain_20ep.py 4** . It still fails. I even exported CUDA_VISIBLE_DEVICES=0,1,2,3 . It didn't hep.

**Comment by suryatechie** [comment]
Found the following process which might be blocking:
0 S **crguest**  10782 10474  0  80   0 -  3555 pipe_w 15:41 pts/0    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox python

Will try to kill and start again.

**Comment by suryatechie** [comment]
Did kill the above process as I am concerned that I might mess up the env.
Found the following online:
_the wrong match due to pytorch version and cuda version. I try torch1.6.0 in cuda10 first and get the same error. I solve the problem by downgrading to torch 1.3.1_

We are having torch 1.6.0 and cuda 10.2

**Comment by suryatechie** [comment]
**torch.cuda.is_available() is false .** 
**Online search:** Sometimes, the issue can be resolved by restarting the system.

**Comment by taeil** [comment]
we can try to recreate a new conda environment to see if that fixes the issue. I will get to it once done with the baseline training.

**Comment by suryatechie** [comment]
I created a new environment and installed older version of torch. The script printed the following but failed in the middle:
Using num gpus: 4
Using num gpus: 4
Removed the environment that I created. Another set of eyes or restart might help.

**Comment by taeil** [comment]
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Using num gpus: 0
Using num gpus: 0
Traceback (most recent call last):
  File "tools/train.py", line 156, in <module>
    main()
  File "tools/train.py", line 93, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 17, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 30, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "tools/train.py", line 156, in <module>
    main()
  File "tools/train.py", line 93, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 17, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 30, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Using num gpus: 0
Traceback (most recent call last):
  File "tools/train.py", line 156, in <module>
    main()
  File "tools/train.py", line 93, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 17, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 30, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Using num gpus: 0
Traceback (most recent call last):
  File "tools/train.py", line 156, in <module>
    main()
  File "tools/train.py", line 93, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 17, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 30, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/scratch/crguest/miniconda3/envs/hp120/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/scratch/crguest/miniconda3/envs/hp120/bin/python', '-u', 'tools/train.py', '--local_rank=3', 'configs/selfsup/moco/r50_v2_resisc_in_basetrain_20ep.py', '--work_dir', 'work_dirs/selfsup/moco/r50_v2_resisc_in_basetrain_20ep/', '--seed', '0', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Comment by taeil** [comment]
someone upgraded the package and it caused the issue. I rolled back. 

```
2021-02-26 14:18:39  (rev 2)
     cudatoolkit  {10.0.130 (defaults/linux-64) -> 10.2.89 (defaults/linux-64)}
     pytorch  {1.2.0 (pytorch/linux-64) -> 1.6.0 (pytorch/linux-64)}
     torchvision  {0.4.0 (pytorch/linux-64) -> 0.7.0 (pytorch/linux-64)}
```

It should be working fine now.

**Comment by suryatechie** [comment]
'Evaluate the representations' part failed as the file 'data/resisc45/meta/train**_**labeled.txt' doesn't exist. In that folder, train**-**labeled.txt file exists.
Did a search in the codebase and found that for file names, '_' and '-' are used interchangeably for some files. So, duplicated the files under 'data/resisc45/meta/' with '**_**' in the file name. It worked fine after the change. 
It ran for 4 hours with 100 epochs.

**Comment by taeil** [comment]
- grouping 
- capturing loss

**Comment by taeil** [comment]
currently this is blocked due to hang on the machine

**Comment by taeil** [comment]
> currently this is blocked due to hang on the machine

This is resolved
